### PR TITLE
Add vlibra.ru in servers.txt

### PR DESCRIPTION
**Pull request by monoreals**

### CODE REVIEW

**Comment by E-404** [comment]
Site unavailable.  Sertificate for domain xmpp.vlibra.ru no valid for site  https://vlibra.ru. Use wildcard https://wiki.404.city/en/Acme.sh  or https://cloudflare.com for main domain vlibra.ru

**Comment by monoreals** [comment]
Corrected.

**Comment by E-404** [comment]
> Corrected.
The site is missing. https://vlibra.ru  403 Forbidden

**Comment by monoreals** [comment]
So sorry.
Corrected all.

**Comment by E-404** [comment]
Do not forget to clarify that **your server is public XMPP server with in-band registration**.  
I think you will do it later, because I add in now, but the now site does not indicate that it is a public server with in-band registration, which may be the reason for the exception when revising the list.

**Comment by monoreals** [comment]
Already fixed. Indicated that this is a public server with in-band registration.

**Pull request merged**
