### PR TITLE
add meckerspace.de

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by E-404** [comment]
Rules
> Conditions for adding to the list.
> It is allowed to add any public server with open registration to this list. On the site that is added to this list must be explicitly stated that this is a public xmpp server and a way to create an account

**Comment by genofire** [comment]
@E-404 it is my own, with open InBand registration

**Comment by E-404** [comment]
I understand that this is a public server with in-band registration, but the user who follows this link will see a blank page. Server directory for visitors. Add words in english or german to the site for example:
> "This is a  XMPP public server with in-band registration"

**Comment by E-404** [comment]
Send a second request if you add a description to the site

**Comment by E-404** [comment]
The site does not claim that it is an XMPP server

**Comment by genofire** [comment]
Now better?

**Comment by E-404** [comment]
> Now better?
Anytime

**Comment by E-404** [comment]
yes

**Pull request merged**
